/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrderRouteImport } from './routes/order'
import { Route as GrainCrumbsProRouteImport } from './routes/grain-crumbs-pro'
import { Route as GrainCrumbsLiteRouteImport } from './routes/grain-crumbs-lite'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as CookieTinsRouteImport } from './routes/cookie-tins'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrowniesRouteImport } from './routes/brownies'
import { Route as BrownieCakesRouteImport } from './routes/brownie-cakes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProRouteImport } from './routes/admin.pro'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLiteRouteImport } from './routes/admin.lite'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminCookieTinsRouteImport } from './routes/admin.cookie-tins'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminCakeFlavoursRouteImport } from './routes/admin.cake-flavours'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const GrainCrumbsProRoute = GrainCrumbsProRouteImport.update({
  id: '/grain-crumbs-pro',
  path: '/grain-crumbs-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const GrainCrumbsLiteRoute = GrainCrumbsLiteRouteImport.update({
  id: '/grain-crumbs-lite',
  path: '/grain-crumbs-lite',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieTinsRoute = CookieTinsRouteImport.update({
  id: '/cookie-tins',
  path: '/cookie-tins',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowniesRoute = BrowniesRouteImport.update({
  id: '/brownies',
  path: '/brownies',
  getParentRoute: () => rootRouteImport,
} as any)
const BrownieCakesRoute = BrownieCakesRouteImport.update({
  id: '/brownie-cakes',
  path: '/brownie-cakes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProRoute = AdminProRouteImport.update({
  id: '/admin/pro',
  path: '/admin/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiteRoute = AdminLiteRouteImport.update({
  id: '/admin/lite',
  path: '/admin/lite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCookieTinsRoute = AdminCookieTinsRouteImport.update({
  id: '/admin/cookie-tins',
  path: '/admin/cookie-tins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCakeFlavoursRoute = AdminCakeFlavoursRouteImport.update({
  id: '/admin/cake-flavours',
  path: '/admin/cake-flavours',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brownie-cakes': typeof BrownieCakesRoute
  '/brownies': typeof BrowniesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-tins': typeof CookieTinsRoute
  '/gifting': typeof GiftingRoute
  '/grain-crumbs-lite': typeof GrainCrumbsLiteRoute
  '/grain-crumbs-pro': typeof GrainCrumbsProRoute
  '/order': typeof OrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/cake-flavours': typeof AdminCakeFlavoursRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/cookie-tins': typeof AdminCookieTinsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/lite': typeof AdminLiteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pro': typeof AdminProRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brownie-cakes': typeof BrownieCakesRoute
  '/brownies': typeof BrowniesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-tins': typeof CookieTinsRoute
  '/gifting': typeof GiftingRoute
  '/grain-crumbs-lite': typeof GrainCrumbsLiteRoute
  '/grain-crumbs-pro': typeof GrainCrumbsProRoute
  '/order': typeof OrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/cake-flavours': typeof AdminCakeFlavoursRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/cookie-tins': typeof AdminCookieTinsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/lite': typeof AdminLiteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pro': typeof AdminProRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brownie-cakes': typeof BrownieCakesRoute
  '/brownies': typeof BrowniesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/cookie-tins': typeof CookieTinsRoute
  '/gifting': typeof GiftingRoute
  '/grain-crumbs-lite': typeof GrainCrumbsLiteRoute
  '/grain-crumbs-pro': typeof GrainCrumbsProRoute
  '/order': typeof OrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/cake-flavours': typeof AdminCakeFlavoursRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/cookie-tins': typeof AdminCookieTinsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/lite': typeof AdminLiteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pro': typeof AdminProRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brownie-cakes'
    | '/brownies'
    | '/cart'
    | '/contact'
    | '/cookie-tins'
    | '/gifting'
    | '/grain-crumbs-lite'
    | '/grain-crumbs-pro'
    | '/order'
    | '/sitemap.xml'
    | '/admin/cake-flavours'
    | '/admin/change-password'
    | '/admin/cookie-tins'
    | '/admin/forgot-password'
    | '/admin/lite'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/pro'
    | '/admin/products'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brownie-cakes'
    | '/brownies'
    | '/cart'
    | '/contact'
    | '/cookie-tins'
    | '/gifting'
    | '/grain-crumbs-lite'
    | '/grain-crumbs-pro'
    | '/order'
    | '/sitemap.xml'
    | '/admin/cake-flavours'
    | '/admin/change-password'
    | '/admin/cookie-tins'
    | '/admin/forgot-password'
    | '/admin/lite'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/pro'
    | '/admin/products'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brownie-cakes'
    | '/brownies'
    | '/cart'
    | '/contact'
    | '/cookie-tins'
    | '/gifting'
    | '/grain-crumbs-lite'
    | '/grain-crumbs-pro'
    | '/order'
    | '/sitemap.xml'
    | '/admin/cake-flavours'
    | '/admin/change-password'
    | '/admin/cookie-tins'
    | '/admin/forgot-password'
    | '/admin/lite'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/pro'
    | '/admin/products'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrownieCakesRoute: typeof BrownieCakesRoute
  BrowniesRoute: typeof BrowniesRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CookieTinsRoute: typeof CookieTinsRoute
  GiftingRoute: typeof GiftingRoute
  GrainCrumbsLiteRoute: typeof GrainCrumbsLiteRoute
  GrainCrumbsProRoute: typeof GrainCrumbsProRoute
  OrderRoute: typeof OrderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCakeFlavoursRoute: typeof AdminCakeFlavoursRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminCookieTinsRoute: typeof AdminCookieTinsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLiteRoute: typeof AdminLiteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProRoute: typeof AdminProRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grain-crumbs-pro': {
      id: '/grain-crumbs-pro'
      path: '/grain-crumbs-pro'
      fullPath: '/grain-crumbs-pro'
      preLoaderRoute: typeof GrainCrumbsProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grain-crumbs-lite': {
      id: '/grain-crumbs-lite'
      path: '/grain-crumbs-lite'
      fullPath: '/grain-crumbs-lite'
      preLoaderRoute: typeof GrainCrumbsLiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-tins': {
      id: '/cookie-tins'
      path: '/cookie-tins'
      fullPath: '/cookie-tins'
      preLoaderRoute: typeof CookieTinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brownies': {
      id: '/brownies'
      path: '/brownies'
      fullPath: '/brownies'
      preLoaderRoute: typeof BrowniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brownie-cakes': {
      id: '/brownie-cakes'
      path: '/brownie-cakes'
      fullPath: '/brownie-cakes'
      preLoaderRoute: typeof BrownieCakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pro': {
      id: '/admin/pro'
      path: '/admin/pro'
      fullPath: '/admin/pro'
      preLoaderRoute: typeof AdminProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lite': {
      id: '/admin/lite'
      path: '/admin/lite'
      fullPath: '/admin/lite'
      preLoaderRoute: typeof AdminLiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cookie-tins': {
      id: '/admin/cookie-tins'
      path: '/admin/cookie-tins'
      fullPath: '/admin/cookie-tins'
      preLoaderRoute: typeof AdminCookieTinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cake-flavours': {
      id: '/admin/cake-flavours'
      path: '/admin/cake-flavours'
      fullPath: '/admin/cake-flavours'
      preLoaderRoute: typeof AdminCakeFlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrownieCakesRoute: BrownieCakesRoute,
  BrowniesRoute: BrowniesRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CookieTinsRoute: CookieTinsRoute,
  GiftingRoute: GiftingRoute,
  GrainCrumbsLiteRoute: GrainCrumbsLiteRoute,
  GrainCrumbsProRoute: GrainCrumbsProRoute,
  OrderRoute: OrderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCakeFlavoursRoute: AdminCakeFlavoursRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminCookieTinsRoute: AdminCookieTinsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLiteRoute: AdminLiteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProRoute: AdminProRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
